version: 0.1.1
default:
  # PostgresSQL
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: "{{ mage_secret_var('POSTGRES_DB') }}"
  POSTGRES_SCHEMA: raw # Optional
  POSTGRES_USER: "{{ mage_secret_var('POSTGRES_USER') }}"
  POSTGRES_PASSWORD: "{{ mage_secret_var('POSTGRES_PASSWORD') }}"
  POSTGRES_HOST: "{{ mage_secret_var('POSTGRES_HOST') }}"
  POSTGRES_PORT: "{{ mage_secret_var('POSTGRES_PORT') }}"